- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Add PostgreSQL repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-9.5 state=latest update_cache=true

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.5/main/pg_hba.conf

- name: Copy valid postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.5/main/postgresql.conf

- name: Restart PostgreSQL
  command: service postgresql restart

- name: Enable start on reboot
  command: update-rc.d postgresql defaults

- name: Create the postgresql user for application
  postgresql_user: name=deploy
  sudo: yes
  sudo_user: postgres

- name: Create the postgresql database for application
  postgresql_db: name=app_{{app_name}} owner=deploy state=present
  sudo: yes
  sudo_user: postgres
